repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
# -   repo: https://github.com/pycqa/flake8
#     rev: '6.1.0'  # pick a git hash / tag to point to
#     hooks:
#     -   id: flake8
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.5.1'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: mypy


